version: '3.9'

services:
  postgres:
    container_name: ecommerce-db
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    volumes:
      - F:\Workspace\Docker\volumes\test:/var/lib/postgresql/data
    ports:
      - "5432:5432"